spring:
  application:
    name: coin_collection

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coin_collection
    username: sa
    password: sa
  jpa:
    show-sql: true
